
before_install:
- sudo curl -L -o /usr/local/bin/mill https://github.com/lihaoyi/mill/releases/download/0.6.1/0.6.1 && sudo chmod +x /usr/local/bin/mill

language: scala

scala:
   - 2.12.10

script:
- mill __.test


