
before_install:
- sudo curl -L -o /usr/local/bin/mill https://github.com/lihaoyi/mill/releases/download/0.2.3/0.2.3 && sudo chmod +x /usr/local/bin/mill

language: scala

scala:
   - 2.12.2

script:
- mill playsonify.test


